##DATA PREPARATION

##define twitter search terms per state
#alkw<-c("alabama,election")
#azkw<-c("arizona,election")
#cokw<-c("colorado,election")
#cnkw<-c("connecticut,election")
#flkw<-c("florida,election")
#gakw<-c("georgia,election")
#idkw<-c("idaho,election")
#inkw<-c("indiana,election")
#lakw<-c("louisiana,election")
#makw<-c("massachusetts,election")
#mnkw<-c("minnesota,election")
#mokw<-c("missouri,election")
#mtkw<-c("montana,election")
#nvkw<-c("nevada,election")
#njkw<-c("new jersey,election")
#nykw<-c("new york,election")
#ndkw<-c("north dakota,election")
#okkw<-c("oklahoma,election")
#pakw<-c("pennsylvania,election")
#sckw<-c("south carolina,election")
#sdkw<-c("south dakota,election")
#txkw<-c("texas,election")
#vtkw<-c("vermont,election")
#wvkw<-c("west virginia,election")
#arkw<-c("arkansas,election")
#cakw<-c("california,election")
#dekw<-c("delaware,election")
#dckw<-c("district of columbia,election")
#ilkw<-c("illinois,election")
#iakw<-c("iowa,election")
#kykw<-c("kentucky,election")
#mekw<-c("maine,election")
#mdkw<-c("maryland,election")
#mikw<-c("michigan,election")
#mskw<-c("mississippi,election")
#nekw<-c("nebraska,election")
#nhkw<-c("new hampshire,election")
#nmkw<-c("new mexico,election")
#nckw<-c("north carolina,election")
#ohkw<-c("ohio,election")
#orkw<-c("oregon,election")
#rikw<-c("rhode island,election")
#tnkw<-c("tennessee,election")
#utkw<-c("utah,election")
#vakw<-c("virginia,election")
#wakw<-c("washington,election")
#wikw<-c("wisonsin,election")
#wvkw<-c("west virginia,election")
#wykw<-c("wyoming,election")

#al_e20<-stream_tweets(q=alkw,timeout = 240,lan='en')
#ar_e20<-stream_tweets(q=arkw,timeout = 240,lan='en')
#az_e20<-stream_tweets(q=azkw,timeout = 240,lan='en')
#ca_e20<-stream_tweets(q=cakw,timeout = 240,lan='en')
#cn_e20<-stream_tweets(q=cnkw,timeout = 240,lan='en')
#co_e20<-stream_tweets(q=cokw,timeout = 240,lan='en')
#dc_e20<-stream_tweets(q=dckw,timeout = 240,lan='en')
#de_e20<-stream_tweets(q=dekw,timeout = 240,lan='en')
#fl_e20<-stream_tweets(q=flkw,timeout = 240,lan='en')
#ga_e20<-stream_tweets(q=gakw,timeout = 240,lan='en')
#ia_e20<-stream_tweets(q=iakw,timeout = 240,lan='en')
#id_e20<-stream_tweets(q=idkw,timeout = 240,lan='en')
#il_e20<-stream_tweets(q=ilkw,timeout = 240,lan='en')
#in_e20<-stream_tweets(q=inkw,timeout = 240,lan='en')
#ks_e20<-stream_tweets(q=kskw,timeout = 240,lan='en')
#ky_e20<-stream_tweets(q=kykw,timeout = 240,lan='en')
#la_e20<-stream_tweets(q=lakw,timeout = 240,lan='en')
#ma_e20<-stream_tweets(q=makw,timeout = 240,lan='en')
#md_e20<-stream_tweets(q=mdkw,timeout = 240,lan='en')
#me_e20<-stream_tweets(q=mekw,timeout = 240,lan='en')
#mi_e20<-stream_tweets(q=mikw,timeout = 240,lan='en')
#mn_e20<-stream_tweets(q=mnkw,timeout = 240,lan='en')
#mo_e20<-stream_tweets(q=mokw,timeout = 240,lan='en')
#ms_e20<-stream_tweets(q=mskw,timeout = 240,lan='en')
#mt_e20<-stream_tweets(q=mtkw,timeout = 240,lan='en')
#nc_e20<-stream_tweets(q=nckw,timeout = 240,lan='en')
#nd_e20<-stream_tweets(q=ndkw,timeout = 240,lan='en')
#ne_e20<-stream_tweets(q=nekw,timeout = 240,lan='en')
#nh_e20<-stream_tweets(q=nhkw,timeout = 240,lan='en')
#nj_e20<-stream_tweets(q=njkw,timeout = 240,lan='en')
#nm_e20<-stream_tweets(q=nmkw,timeout = 240,lan='en')
#nv_e20<-stream_tweets(q=nvkw,timeout = 240,lan='en')
#ny_e20<-stream_tweets(q=nykw,timeout = 240,lan='en')
#oh_e20<-stream_tweets(q=ohkw,timeout = 240,lan='en')
#ok_e20<-stream_tweets(q=okkw,timeout = 240,lan='en')
#or_e20<-stream_tweets(q=orkw,timeout = 240,lan='en')
#pa_e20<-stream_tweets(q=pakw,timeout = 240,lan='en')
#ri_e20<-stream_tweets(q=rikw,timeout = 240,lan='en')
#sc_e20<-stream_tweets(q=sckw,timeout = 240,lan='en')
#sd_e20<-stream_tweets(q=sdkw,timeout = 240,lan='en')
#tn_e20<-stream_tweets(q=tnkw,timeout = 240,lan='en')
#tx_e20<-stream_tweets(q=txkw,timeout = 240,lan='en')
#ut_e20<-stream_tweets(q=utkw,timeout = 240,lan='en')
#va_e20<-stream_tweets(q=vakw,timeout = 240,lan='en')
#vt_e20<-stream_tweets(q=vtkw,timeout = 240,lan='en')
#wa_e20<-stream_tweets(q=wakw,timeout = 240,lan='en')
#wi_e20<-stream_tweets(q=wikw,timeout = 240,lan='en')
#wv_e20<-stream_tweets(q=wvkw,timeout = 240,lan='en')
#wy_e20<-stream_tweets(q=wykw,timeout = 240,lan='en')

#al20<-tibble(1:6883,al_e20)
#ar20<-tibble(1:6237,ar_e20)
#az20<-tibble(1:6285,az_e20)
#ca20<-tibble(1:6252,ca_e20)
#cn20<-tibble(1:6434,cn_e20)
#co20<-tibble(1:6386,co_e20)
#dc20<-tibble(1:6451,dc_e20)
#de20<-tibble(1:6407,de_e20)
#fl20<-tibble(1:6312,fl_e20)
#ga20<-tibble(1:6950,ga_e20)
#ia20<-tibble(1:6449,ia_e20)
#id20<-tibble(1:6336,id_e20)
#il20<-tibble(1:6641,il_e20)
#in20<-tibble(1:6568,in_e20)
#ks20<-tibble(1:6598,ks_e20)
#ky20<-tibble(1:6614,ky_e20)
#la20<-tibble(1:6547,la_e20)
#ma20<-tibble(1:6398,ma_e20)
#md20<-tibble(1:6403,md_e20)
#me20<-tibble(1:6453,me_e20)
#mi20<-tibble(1:6374,mi_e20)
#mn20<-tibble(1:7172,mn_e20)
#mo20<-tibble(1:6923,mo_e20)
#ms20<-tibble(1:6863,ms_e20)
#mt20<-tibble(1:6814,mt_e20)
#nc20<-tibble(1:6622,nc_e20)
#nd20<-tibble(1:6743,nd_e20)
#ne20<-tibble(1:6752,ne_e20)
#nh20<-tibble(1:6711,nh_e20)
#nj20<-tibble(1:6618,nj_e20)
#nm20<-tibble(1:6736,nm_e20)
#nv20<-tibble(1:6631,nv_e20)
#ny20<-tibble(1:6532,ny_e20)
#oh20<-tibble(1:6527,oh_e20)
#ok20<-tibble(1:6449,ok_e20)
#or20<-tibble(1:6431,or_e20)
#pa20<-tibble(1:6656,pa_e20)
#ri20<-tibble(1:6419,ri_e20)
#sc20<-tibble(1:6450,sc_e20)
#sd20<-tibble(1:6476,sd_e20)
#tn20<-tibble(1:6500,tn_e20)
#tx20<-tibble(1:6180,tx_e20)
#ut20<-tibble(1:6207,ut_e20)
#va20<-tibble(1:6273,va_e20)
#vt20<-tibble(1:6543,vt_e20)
#wa20<-tibble(1:6349,wa_e20)
#wi20<-tibble(1:6102,wi_e20)
#wv20<-tibble(1:6380,wv_e20)
#wy20<-tibble(1:6186,wy_e20)

#write_as_csv(al20,"elxn_al.csv")
#write_as_csv(ar20,"elxn_ar.csv")
#write_as_csv(az20,"elxn_az.csv")
#write_as_csv(ca20,"elxn_ca.csv")
#write_as_csv(cn20,"elxn_cn.csv")
#write_as_csv(co20,"elxn_co.csv")
#write_as_csv(dc20,"elxn_dc.csv")
#write_as_csv(de20,"elxn_de.csv")
#write_as_csv(fl20,"elxn_fl.csv")
#write_as_csv(ga20,"elxn_ga.csv")
#write_as_csv(ia20,"elxn_ia.csv")
#write_as_csv(id20,"elxn_id.csv")
#write_as_csv(il20,"elxn_il.csv")
#write_as_csv(in20,"elxn_in.csv")
#write_as_csv(ks20,"elxn_ks.csv")
#write_as_csv(ky20,"elxn_ky.csv")
#write_as_csv(la20,"elxn_la.csv")
#write_as_csv(ma20,"elxn_ma.csv")
#write_as_csv(md20,"elxn_md.csv")
#write_as_csv(me20,"elxn_me.csv")
#write_as_csv(mi20,"elxn_mi.csv")
#write_as_csv(mn20,"elxn_mn.csv")
#write_as_csv(mo20,"elxn_mo.csv")
#write_as_csv(ms20,"elxn_ms.csv")
#write_as_csv(mt20,"elxn_mt.csv")
#write_as_csv(nc20,"elxn_nc.csv")
#write_as_csv(nd20,"elxn_nd.csv")
#write_as_csv(ne20,"elxn_ne.csv")
#write_as_csv(nh20,"elxn_nh.csv")
#write_as_csv(nj20,"elxn_nj.csv")
#write_as_csv(nm20,"elxn_nm.csv")
#write_as_csv(nv20,"elxn_nv.csv")
#write_as_csv(ny20,"elxn_ny.csv")
#write_as_csv(oh20,"elxn_oh.csv")
#write_as_csv(ok20,"elxn_ok.csv")
#write_as_csv(or20,"elxn_or.csv")
#write_as_csv(pa20,"elxn_pa.csv")
#write_as_csv(ri20,"elxn_ri.csv")
#write_as_csv(sc20,"elxn_sc.csv")
#write_as_csv(sd20,"elxn_sd.csv")
#write_as_csv(tn20,"elxn_tn.csv")
#write_as_csv(tx20,"elxn_tx.csv")
#write_as_csv(ut20,"elxn_ut.csv")
#write_as_csv(va20,"elxn_va.csv")
#write_as_csv(vt20,"elxn_vt.csv")
#write_as_csv(wa20,"elxn_wa.csv")
#write_as_csv(wi20,"elxn_wi.csv")
#write_as_csv(wv20,"elxn_wv.csv")
#write_as_csv(wy20,"elxn_wy.csv")

#write_as_csv(exn_al,"elxn_al.csv")
#write_as_csv(exn_ar,"elxn_ar.csv")
#write_as_csv(exn_az,"elxn_az.csv")
#write_as_csv(exn_ca,"elxn_ca.csv")
#write_as_csv(exn_cn,"elxn_cn.csv")
#write_as_csv(exn_co,"elxn_co.csv")
#write_as_csv(exn_dc,"elxn_dc.csv")
#write_as_csv(exn_de,"elxn_de.csv")
#write_as_csv(exn_fl,"elxn_fl.csv")
#write_as_csv(exn_ga,"elxn_ga.csv")
#write_as_csv(exn_ia,"elxn_ia.csv")
#write_as_csv(exn_id,"elxn_id.csv")
#write_as_csv(exn_il,"elxn_il.csv")
#write_as_csv(exn_in,"elxn_in.csv")
#write_as_csv(exn_ks,"elxn_ks.csv")
#write_as_csv(exn_ky,"elxn_ky.csv")
#write_as_csv(exn_la,"elxn_la.csv")
#write_as_csv(exn_ma,"elxn_ma.csv")
#write_as_csv(exn_md,"elxn_md.csv")
#write_as_csv(exn_me,"elxn_me.csv")
#write_as_csv(exn_mi,"elxn_mi.csv")
#write_as_csv(exn_mn,"elxn_mn.csv")
#write_as_csv(exn_mo,"elxn_mo.csv")
#write_as_csv(exn_ms,"elxn_ms.csv")
#write_as_csv(exn_mt,"elxn_mt.csv")
#write_as_csv(exn_nc,"elxn_nc.csv")
#write_as_csv(exn_nd,"elxn_nd.csv")
#write_as_csv(exn_ne,"elxn_ne.csv")
#write_as_csv(exn_nh,"elxn_nh.csv")
#write_as_csv(exn_nj,"elxn_nj.csv")
#write_as_csv(exn_nm,"elxn_nm.csv")
#write_as_csv(exn_nv,"elxn_nv.csv")
#write_as_csv(exn_ny,"elxn_ny.csv")
#write_as_csv(exn_oh,"elxn_oh.csv")
#write_as_csv(exn_ok,"elxn_ok.csv")
#write_as_csv(exn_or,"elxn_or.csv")
#write_as_csv(exn_pa,"elxn_pa.csv")
#write_as_csv(exn_ri,"elxn_ri.csv")
#write_as_csv(exn_sc,"elxn_sc.csv")
#write_as_csv(exn_sd,"elxn_sd.csv")
#write_as_csv(exn_tn,"elxn_tn.csv")
#write_as_csv(exn_tx,"elxn_tx.csv")
#write_as_csv(exn_ut,"elxn_ut.csv")
#write_as_csv(exn_va,"elxn_va.csv")
#write_as_csv(exn_vt,"elxn_vt.csv")
#write_as_csv(exn_wa,"elxn_wa.csv")
#write_as_csv(exn_wi,"elxn_wi.csv")
#write_as_csv(exn_wv,"elxn_wv.csv")
#write_as_csv(exn_wy,"elxn_wy.csv")

##READ IN CSV FILES FROM ZIPPED data file

#exn_al<-read.csv("elxn_al.csv")
#exn_ar<-read.csv("elxn_ar.csv")
#exn_az<-read.csv("elxn_az.csv")
#exn_ca<-read.csv("elxn_ca.csv")
#exn_cn<-read.csv("elxn_cn.csv")
#exn_co<-read.csv("elxn_co.csv")
#exn_dc<-read.csv("elxn_dc.csv")
#exn_de<-read.csv("elxn_de.csv")
#exn_fl<-read.csv("elxn_fl.csv")
#exn_ga<-read.csv("elxn_ga.csv")
#exn_ia<-read.csv("elxn_ia.csv")
#exn_id<-read.csv("elxn_id.csv")
#exn_il<-read.csv("elxn_il.csv")
#exn_in<-read.csv("elxn_in.csv")
#exn_ks<-read.csv("elxn_ks.csv")
#exn_ky<-read.csv("elxn_ky.csv")
#exn_la<-read.csv("elxn_la.csv")
#exn_ma<-read.csv("elxn_ma.csv")
#exn_md<-read.csv("elxn_md.csv")
#exn_me<-read.csv("elxn_me.csv")
#exn_mi<-read.csv("elxn_mi.csv")
#exn_mn<-read.csv("elxn_mn.csv")
#exn_mo<-read.csv("elxn_mo.csv")
#exn_ms<-read.csv("elxn_ms.csv")
#exn_mt<-read.csv("elxn_mt.csv")
#exn_nc<-read.csv("elxn_nc.csv")
#exn_nd<-read.csv("elxn_nd.csv")
#exn_ne<-read.csv("elxn_ne.csv")
#exn_nh<-read.csv("elxn_nh.csv")
#exn_nj<-read.csv("elxn_nj.csv")
#exn_nm<-read.csv("elxn_nm.csv")
#exn_nv<-read.csv("elxn_nv.csv")
#exn_ny<-read.csv("elxn_ny.csv")
#exn_oh<-read.csv("elxn_oh.csv")
#exn_ok<-read.csv("elxn_ok.csv")
#exn_or<-read.csv("elxn_or.csv")
#exn_pa<-read.csv("elxn_pa.csv")
#exn_ri<-read.csv("elxn_ri.csv")
#exn_sc<-read.csv("elxn_sc.csv")
#exn_sd<-read.csv("elxn_sd.csv")
#exn_tn<-read.csv("elxn_tn.csv")
#exn_tx<-read.csv("elxn_tx.csv")
#exn_ut<-read.csv("elxn_ut.csv")
#exn_va<-read.csv("elxn_va.csv")
#exn_vt<-read.csv("elxn_vt.csv")
#exn_wa<-read.csv("elxn_wa.csv")
#exn_wi<-read.csv("elxn_wi.csv")
#exn_wv<-read.csv("elxn_wv.csv")
#exn_wy<-read.csv("elxn_wy.csv")

#FORMATTING DATA FRAME

#txt_al<-tibble(1:6883,exn_al$text)
#names(txt_al)<-c("tweet","text")
#txt_al$location<-"Alabama"
#txt_ar<-tibble(1:6237,exn_ar$text)
#names(txt_ar)<-c("tweet","text")
#txt_ar$location<-"Arkansas"
#txt_az<-tibble(1:6285,exn_az$text)
#names(txt_az)<-c("tweet","text")
#txt_az$location<-"Arizona"
#txt_ca<-tibble(1:6252,exn_ca$text)
#names(txt_ca)<-c("tweet","text")
#txt_ca$location<-"California"
#txt_cn<-tibble(1:6434,exn_cn$text)
#names(txt_cn)<-c("tweet","text")
#txt_cn$location<-"Connecticut"
#txt_co<-tibble(1:6386,exn_co$text)
#names(txt_co)<-c("tweet","text")
#txt_co$location<-"Colorado"
#txt_dc<-tibble(1:6451,exn_dc$text)
#names(txt_dc)<-c("tweet","text")
#txt_dc$location<-"District of Columbia"
#txt_de<-tibble(1:6407,exn_de$text)
#names(txt_de)<-c("tweet","text")
#txt_de$location<-"Delaware"
#txt_fl<-tibble(1:6312,exn_fl$text)
#names(txt_fl)<-c("tweet","text")
#txt_fl$location<-"Florida"
#txt_ga<-tibble(1:6950,exn_ga$text)
#names(txt_ga)<-c("tweet","text")
#txt_ga$location<-"Georgia"
#txt_ia<-tibble(1:6449,exn_ia$text)
#names(txt_ia)<-c("tweet","text")
#txt_ia$location<-"Iowa"
#txt_id<-tibble(1:6336,exn_id$text)
#names(txt_id)<-c("tweet","text")
#txt_id$location<-"Idaho"
#txt_il<-tibble(1:6641,exn_il$text)
#names(txt_il)<-c("tweet","text")
#txt_il$location<-"Illonois"
#txt_in<-tibble(1:6568,exn_in$text)
#names(txt_in)<-c("tweet","text")
#txt_in$location<-"Indiana"
#txt_ks<-tibble(1:6598,exn_ks$text)
#names(txt_ks)<-c("tweet","text")
#txt_ks$location<-"Kansas"
#txt_ky<-tibble(1:6614,exn_ky$text)
#names(txt_ky)<-c("tweet","text")
#txt_ky$location<-"Kentucky"
#txt_la<-tibble(1:6547,exn_la$text)
#names(txt_la)<-c("tweet","text")
#txt_la$location<-"Louisiana"
#txt_ma<-tibble(1:6398,exn_ma$text)
#names(txt_ma)<-c("tweet","text")
#txt_ma$location<-"Massachusetts"
#txt_md<-tibble(1:6403,exn_md$text)
#names(txt_md)<-c("tweet","text")
#txt_md$location<-"Maryland"
#txt_me<-tibble(1:6453,exn_me$text)
#names(txt_me)<-c("tweet","text")
#txt_me$location<-"Maine"
#txt_mi<-tibble(1:6374,exn_mi$text)
#names(txt_mi)<-c("tweet","text")
#txt_mi$location<-"Michigan"
#txt_mn<-tibble(1:7172,exn_mn$text)
#names(txt_mn)<-c("tweet","text")
#txt_mn$location<-"Minnesota"
#txt_mo<-tibble(1:6923,exn_mo$text)
#names(txt_mo)<-c("tweet","text")
#txt_mo$location<-"Missouri"
#txt_ms<-tibble(1:6863,exn_ms$text)
#names(txt_ms)<-c("tweet","text")
#txt_ms$location<-"Mississippi"
#txt_mt<-tibble(1:6814,exn_mt$text)
#names(txt_mt)<-c("tweet","text")
#txt_mt$location<-"Montana"
#txt_nc<-tibble(1:6622,exn_nc$text)
#names(txt_nc)<-c("tweet","text")
#txt_nc$location<-"North Carolina"
#txt_nd<-tibble(1:6743,exn_nd$text)
#names(txt_nd)<-c("tweet","text")
#txt_nd$location<-"North Dakota"
#txt_ne<-tibble(1:6752,exn_ne$text)
#names(txt_ne)<-c("tweet","text")
#txt_ne$location<-"Nebraska"
#txt_nh<-tibble(1:6711,exn_nh$text)
#names(txt_nh)<-c("tweet","text")
#txt_nh$location<-"New Hampshire"
#txt_nj<-tibble(1:6618,exn_nj$text)
#names(txt_nj)<-c("tweet","text")
#txt_nj$location<-"New Jersey"
#txt_nm<-tibble(1:6736,exn_nm$text)
#names(txt_nm)<-c("tweet","text")
#txt_nm$location<-"New Mexico"
#txt_nv<-tibble(1:6631,exn_nv$text)
#names(txt_nv)<-c("tweet","text")
#txt_nv$location<-"Nevada"
#txt_ny<-tibble(1:6532,exn_ny$text)
#names(txt_ny)<-c("tweet","text")
#txt_ny$location<-"New York"
#txt_oh<-tibble(1:6527,exn_oh$text)
#names(txt_oh)<-c("tweet","text")
#txt_oh$location<-"Ohio"
#txt_ok<-tibble(1:6449,exn_ok$text)
#names(txt_ok)<-c("tweet","text")
#txt_ok$location<-"Oklahoma"
#txt_or<-tibble(1:6431,exn_or$text)
#names(txt_or)<-c("tweet","text")
#txt_or$location<-"Oregon"
#txt_pa<-tibble(1:6656,exn_pa$text)
#names(txt_pa)<-c("tweet","text")
#txt_pa$location<-"Pennsylvania"
#txt_ri<-tibble(1:6419,exn_ri$text)
#names(txt_ri)<-c("tweet","text")
#txt_ri$location<-"Rhode Island"
#txt_sc<-tibble(1:6450,exn_sc$text)
#names(txt_sc)<-c("tweet","text")
#txt_sc$location<-"South Carolina"
#txt_sd<-tibble(1:6476,exn_sd$text)
#names(txt_sd)<-c("tweet","text")
#txt_sd$location<-"South Dakota"
#txt_tn<-tibble(1:6500,exn_tn$text)
#names(txt_tn)<-c("tweet","text")
#txt_tn$location<-"Tennessee"
#txt_tx<-tibble(1:6180,exn_tx$text)
#names(txt_tx)<-c("tweet","text")
#txt_tx$location<-"Texas"
#txt_ut<-tibble(1:6207,exn_ut$text)
#names(txt_ut)<-c("tweet","text")
#txt_ut$location<-"Utah"
#txt_va<-tibble(1:6273,exn_va$text)
#names(txt_va)<-c("tweet","text")
#txt_va$location<-"Virginia"
#txt_vt<-tibble(1:6543,exn_vt$text)
#names(txt_vt)<-c("tweet","text")
#txt_vt$location<-"Vermont"
#txt_wa<-tibble(1:6349,exn_wa$text)
#names(txt_wa)<-c("tweet","text")
#txt_wa$location<-"Washington"
#txt_wi<-tibble(1:6102,exn_wi$text)
#names(txt_wi)<-c("tweet","text")
#txt_wi$location<-"Wisconsin"
#txt_wv<-tibble(1:6380,exn_wv$text)
#names(txt_wv)<-c("tweet","text")
#txt_wv$location<-"West Virginia"
#txt_wy<-tibble(1:6186,exn_wy$text)
#names(txt_wy)<-c("tweet","text")
#txt_wy$location<-"Wyoming"

#write_as_csv(txt_al,"txt_al.csv")
#write_as_csv(txt_ar,"txt_ar.csv")
#write_as_csv(txt_az,"txt_az.csv")
#write_as_csv(txt_ca,"txt_ca.csv")
#write_as_csv(txt_cn,"txt_cn.csv")
#write_as_csv(txt_co,"txt_co.csv")
#write_as_csv(txt_dc,"txt_dc.csv")
#write_as_csv(txt_de,"txt_de.csv")
#write_as_csv(txt_fl,"txt_fl.csv")
#write_as_csv(txt_ga,"txt_ga.csv")
#write_as_csv(txt_ia,"txt_ia.csv")
#write_as_csv(txt_id,"txt_id.csv")
#write_as_csv(txt_il,"txt_il.csv")
#write_as_csv(txt_in,"txt_in.csv")
#write_as_csv(txt_ks,"txt_ks.csv")
#write_as_csv(txt_ky,"txt_ky.csv")
#write_as_csv(txt_la,"txt_la.csv")
#write_as_csv(txt_ma,"txt_ma.csv")
#write_as_csv(txt_md,"txt_md.csv")
#write_as_csv(txt_me,"txt_me.csv")
#write_as_csv(txt_mi,"txt_mi.csv")
#write_as_csv(txt_mn,"txt_mn.csv")
#write_as_csv(txt_mo,"txt_mo.csv")
#write_as_csv(txt_ms,"txt_ms.csv")
#write_as_csv(txt_mt,"txt_mt.csv")
#write_as_csv(txt_nc,"txt_nc.csv")
#write_as_csv(txt_nd,"txt_nd.csv")
#write_as_csv(txt_ne,"txt_ne.csv")
#write_as_csv(txt_nh,"txt_nh.csv")
#write_as_csv(txt_nj,"txt_nj.csv")
#write_as_csv(txt_nm,"txt_nm.csv")
#write_as_csv(txt_nv,"txt_nv.csv")
#write_as_csv(txt_ny,"txt_ny.csv")
#write_as_csv(txt_oh,"txt_oh.csv")
#write_as_csv(txt_ok,"txt_ok.csv")
#write_as_csv(txt_or,"txt_or.csv")
#write_as_csv(txt_pa,"txt_pa.csv")
#write_as_csv(txt_ri,"txt_ri.csv")
#write_as_csv(txt_sc,"txt_sc.csv")
#write_as_csv(txt_sd,"txt_sd.csv")
#write_as_csv(txt_tn,"txt_tn.csv")
#write_as_csv(txt_tx,"txt_tx.csv")
#write_as_csv(txt_ut,"txt_ut.csv")
#write_as_csv(txt_va,"txt_va.csv")
#write_as_csv(txt_vt,"txt_vt.csv")
#write_as_csv(txt_wa,"txt_wa.csv")
#write_as_csv(txt_wi,"txt_wi.csv")
#write_as_csv(txt_wv,"txt_wv.csv")
#write_as_csv(txt_wy,"txt_wy.csv")